// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// CppScore
arma::vec CppScore(arma::mat X, arma::vec v, arma::mat Rhat, arma::vec y, arma::vec mu, int N, float phi, arma::vec w);
RcppExport SEXP _pgee_mixed_CppScore(SEXP XSEXP, SEXP vSEXP, SEXP RhatSEXP, SEXP ySEXP, SEXP muSEXP, SEXP NSEXP, SEXP phiSEXP, SEXP wSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type v(vSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Rhat(RhatSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::vec >::type mu(muSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< float >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type w(wSEXP);
    rcpp_result_gen = Rcpp::wrap(CppScore(X, v, Rhat, y, mu, N, phi, w));
    return rcpp_result_gen;
END_RCPP
}
// CppHess
arma::mat CppHess(arma::mat X, arma::vec v, arma::mat Rhat, float phi, int N, arma::vec w);
RcppExport SEXP _pgee_mixed_CppHess(SEXP XSEXP, SEXP vSEXP, SEXP RhatSEXP, SEXP phiSEXP, SEXP NSEXP, SEXP wSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type v(vSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Rhat(RhatSEXP);
    Rcpp::traits::input_parameter< float >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type w(wSEXP);
    rcpp_result_gen = Rcpp::wrap(CppHess(X, v, Rhat, phi, N, w));
    return rcpp_result_gen;
END_RCPP
}
// CppM
arma::mat CppM(arma::vec y, arma::mat X, arma::vec mu, arma::vec v, arma::mat Rhat, float phi, int N, arma::vec w);
RcppExport SEXP _pgee_mixed_CppM(SEXP ySEXP, SEXP XSEXP, SEXP muSEXP, SEXP vSEXP, SEXP RhatSEXP, SEXP phiSEXP, SEXP NSEXP, SEXP wSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type mu(muSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type v(vSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Rhat(RhatSEXP);
    Rcpp::traits::input_parameter< float >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type w(wSEXP);
    rcpp_result_gen = Rcpp::wrap(CppM(y, X, mu, v, Rhat, phi, N, w));
    return rcpp_result_gen;
END_RCPP
}
// CppIncBeta
arma::vec CppIncBeta(Rcpp::NumericVector beta, Rcpp::NumericVector score, Rcpp::NumericMatrix Hess, Rcpp::NumericMatrix Emat, int n);
RcppExport SEXP _pgee_mixed_CppIncBeta(SEXP betaSEXP, SEXP scoreSEXP, SEXP HessSEXP, SEXP EmatSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type score(scoreSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type Hess(HessSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type Emat(EmatSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(CppIncBeta(beta, score, Hess, Emat, n));
    return rcpp_result_gen;
END_RCPP
}
// CppAlphaCS
float CppAlphaCS(arma::vec pres, arma::vec w, int m, int p, float phi);
RcppExport SEXP _pgee_mixed_CppAlphaCS(SEXP presSEXP, SEXP wSEXP, SEXP mSEXP, SEXP pSEXP, SEXP phiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type pres(presSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type w(wSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< float >::type phi(phiSEXP);
    rcpp_result_gen = Rcpp::wrap(CppAlphaCS(pres, w, m, p, phi));
    return rcpp_result_gen;
END_RCPP
}
// CppAlphaAR1
float CppAlphaAR1(arma::vec pres, arma::vec w, int m, int p, float phi);
RcppExport SEXP _pgee_mixed_CppAlphaAR1(SEXP presSEXP, SEXP wSEXP, SEXP mSEXP, SEXP pSEXP, SEXP phiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type pres(presSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type w(wSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< float >::type phi(phiSEXP);
    rcpp_result_gen = Rcpp::wrap(CppAlphaAR1(pres, w, m, p, phi));
    return rcpp_result_gen;
END_RCPP
}
// PenScore
arma::vec PenScore(Rcpp::NumericVector beta, Rcpp::NumericVector score, Rcpp::NumericMatrix Emat, int n);
RcppExport SEXP _pgee_mixed_PenScore(SEXP betaSEXP, SEXP scoreSEXP, SEXP EmatSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type score(scoreSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type Emat(EmatSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(PenScore(beta, score, Emat, n));
    return rcpp_result_gen;
END_RCPP
}
// samemats
bool samemats(arma::mat X, arma::mat Y);
RcppExport SEXP _pgee_mixed_samemats(SEXP XSEXP, SEXP YSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Y(YSEXP);
    rcpp_result_gen = Rcpp::wrap(samemats(X, Y));
    return rcpp_result_gen;
END_RCPP
}
// CppW
arma::mat CppW(arma::mat X, arma::vec v, arma::mat Rhat, int N);
RcppExport SEXP _pgee_mixed_CppW(SEXP XSEXP, SEXP vSEXP, SEXP RhatSEXP, SEXP NSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type v(vSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Rhat(RhatSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    rcpp_result_gen = Rcpp::wrap(CppW(X, v, Rhat, N));
    return rcpp_result_gen;
END_RCPP
}
// CppHess2
arma::mat CppHess2(arma::mat X, arma::vec v, float alpha, float phi, int N, arma::vec w);
RcppExport SEXP _pgee_mixed_CppHess2(SEXP XSEXP, SEXP vSEXP, SEXP alphaSEXP, SEXP phiSEXP, SEXP NSEXP, SEXP wSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type v(vSEXP);
    Rcpp::traits::input_parameter< float >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< float >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type w(wSEXP);
    rcpp_result_gen = Rcpp::wrap(CppHess2(X, v, alpha, phi, N, w));
    return rcpp_result_gen;
END_RCPP
}
// CppScore2
arma::vec CppScore2(arma::mat X, arma::vec v, float alpha, arma::vec y, arma::vec mu, int N, float phi, arma::vec w);
RcppExport SEXP _pgee_mixed_CppScore2(SEXP XSEXP, SEXP vSEXP, SEXP alphaSEXP, SEXP ySEXP, SEXP muSEXP, SEXP NSEXP, SEXP phiSEXP, SEXP wSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type v(vSEXP);
    Rcpp::traits::input_parameter< float >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::vec >::type mu(muSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< float >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type w(wSEXP);
    rcpp_result_gen = Rcpp::wrap(CppScore2(X, v, alpha, y, mu, N, phi, w));
    return rcpp_result_gen;
END_RCPP
}
// CppM2
arma::mat CppM2(arma::vec y, arma::mat X, arma::vec mu, arma::vec v, float alpha, float phi, int N, arma::vec w);
RcppExport SEXP _pgee_mixed_CppM2(SEXP ySEXP, SEXP XSEXP, SEXP muSEXP, SEXP vSEXP, SEXP alphaSEXP, SEXP phiSEXP, SEXP NSEXP, SEXP wSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type mu(muSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type v(vSEXP);
    Rcpp::traits::input_parameter< float >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< float >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type w(wSEXP);
    rcpp_result_gen = Rcpp::wrap(CppM2(y, X, mu, v, alpha, phi, N, w));
    return rcpp_result_gen;
END_RCPP
}
// CppW2
arma::mat CppW2(arma::mat X, arma::vec v, arma::mat Rhat, int N, arma::vec w);
RcppExport SEXP _pgee_mixed_CppW2(SEXP XSEXP, SEXP vSEXP, SEXP RhatSEXP, SEXP NSEXP, SEXP wSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type v(vSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Rhat(RhatSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type w(wSEXP);
    rcpp_result_gen = Rcpp::wrap(CppW2(X, v, Rhat, N, w));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_pgee_mixed_CppScore", (DL_FUNC) &_pgee_mixed_CppScore, 8},
    {"_pgee_mixed_CppHess", (DL_FUNC) &_pgee_mixed_CppHess, 6},
    {"_pgee_mixed_CppM", (DL_FUNC) &_pgee_mixed_CppM, 8},
    {"_pgee_mixed_CppIncBeta", (DL_FUNC) &_pgee_mixed_CppIncBeta, 5},
    {"_pgee_mixed_CppAlphaCS", (DL_FUNC) &_pgee_mixed_CppAlphaCS, 5},
    {"_pgee_mixed_CppAlphaAR1", (DL_FUNC) &_pgee_mixed_CppAlphaAR1, 5},
    {"_pgee_mixed_PenScore", (DL_FUNC) &_pgee_mixed_PenScore, 4},
    {"_pgee_mixed_samemats", (DL_FUNC) &_pgee_mixed_samemats, 2},
    {"_pgee_mixed_CppW", (DL_FUNC) &_pgee_mixed_CppW, 4},
    {"_pgee_mixed_CppHess2", (DL_FUNC) &_pgee_mixed_CppHess2, 6},
    {"_pgee_mixed_CppScore2", (DL_FUNC) &_pgee_mixed_CppScore2, 8},
    {"_pgee_mixed_CppM2", (DL_FUNC) &_pgee_mixed_CppM2, 8},
    {"_pgee_mixed_CppW2", (DL_FUNC) &_pgee_mixed_CppW2, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_pgee_mixed(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
